services:
  web:
    container_name: fastapi
    build: .
    image: fastapp
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    
    environment:
      - host=web
    
    networks:
      - appnet
    restart: always
  
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    
    ports:
      - 5432:5432
    
    networks:
      - appnet
    
    restart: always
  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - appnet
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=default
    restart: always

    command: redis-server --requirepass ${REDIS_PASSWORD}
  
networks:
  appnet:
    
    